### ISSUE TITLE
Better handling of GNOME crashes caused by xwayland dying

### ISSUE THREAD

**Issue by AdamWill** [abrt/satyr#271]
After having unpicked all the dupes caused by RHBZ 1509086, it seems to me there's one more case that we should probably handle carefully in abrt/satyr: the case where GNOME is basically taken down by XWayland crashing. Almost always when that happens we get a backtrace that runs through these frames:

     #0 _g_log_abort at gmessages.c:549
     #1 g_log_default_handler at gmessages.c:3036
     #2 default_log_handler at main.c:303
     #5 x_io_error at wayland/meta-xwayland.c:411

with the fatal log message being "Connection to xwayland lost". But the rest of the backtrace may be different, and I believe the backtrace is usually going to be useless anyway; what GNOME was doing at the time it noticed that XWayland had gone away probably isn't relevant to the cause of the XWayland crash, which most of the time is going to be a graphics driver bug.

Here are some examples of bugs like this:

* https://bugzilla.redhat.com/show_bug.cgi?id=1497857
* https://bugzilla.redhat.com/show_bug.cgi?id=1497447
* https://bugzilla.redhat.com/show_bug.cgi?id=1526367
* https://bugzilla.redhat.com/show_bug.cgi?id=1517009 (this is actually a rather interesting case I might file another issue on)
* https://bugzilla.redhat.com/show_bug.cgi?id=1524214
* https://bugzilla.redhat.com/show_bug.cgi?id=1470883

Sorry that they're private, if someone without the necessary privs needs to look at them, let me know and we can try to figure something out.

I think what's most important to do in cases like this is isolate the XWayland traceback from the system logs, and possibly to collect info on the graphics adapter and any logged errors from the graphics subsystems, but graphics / GNOME devs might have other suggestions, so I'll tag some of them to see if they have thoughts on how abrt should handle these crashes: @nwnk @airlied @matthiasclasen @owtaylor

**Comment by AdamWill** [comment]
This is now becoming a real problem. https://bugzilla.redhat.com/show_bug.cgi?id=1510059 is getting a flood of dupes of exactly this nature: it seems like any time Shell crashes down this path, it gets marked as a dupe of that bug, even though all these reports don't have anything much to do with each other except that Shell went down because XWayland went down.

That bug currently has 121 duplicates, and 89 "Similar problem has been detected" comments (libreport creates a new bug and immediately marks it as a dupe if the report is marked as containing 'private' information, but adds a 'Similar problem has been detected' comment if it isn't). So that's 210 probably different crashes all erroneously being treated as "dupes" of that bug.

**Comment by marusak** [comment]
@mhabrnal haven't you fixed this?

**Comment by AdamWill** [comment]
If so, it doesn't appear to have reached F27, at least...important fixes need to get sent out as updates to stable Fedora releases, or else we'll keep getting bad reports from those releases until they go EOL.

**Comment by mhabrnal** [comment]
It was mostly fixed by commit https://github.com/abrt/satyr/commit/6383faff4959c751f71f107901897ff654e82615 a few months ago.

I've actualized a list of normalization functions according to https://bugzilla.redhat.com/show_bug.cgi?id=1510059 (https://github.com/abrt/satyr/pull/280)

**Comment by AdamWill** [comment]
Yeah, I recall when we went through this back then. Whatever change has been made clearly wasn't sufficient, though, as we're still getting dupes of 1510059 constantly. It looks like that recent commit should help, if we can get that sent out to F27 (and probably F28 and Rawhide). Thanks.
